### ISSUE TITLE
Parrots on shoulders are not the right texture (ETF Issue)

### ISSUE THREAD

**Issue by U5B** [U5B/MonumentaRP-NoOptiFine#2]

**Comment by U5B** [comment]
Yay! https://github.com/Traben-0/Entity_Texture_Features/commit/3d32da5c6fff58e8ffaff904e81b4e1acf9a6d6b
Now to wait for a release or compile it...

**Comment by U5B** [comment]
Use this build until v2.6.1 releases! https://github.com/Traben-0/Entity_Texture_Features/suites/6202307482/artifacts/218796418

**Comment by Vladomeme** [comment]
Fixed in ETF v4.1.1
