### ISSUE TITLE
Tridents are not textured

### ISSUE THREAD

**Issue by U5B** [U5B/MonumentaRP-NoOptiFine#3]

**Comment by U5B** [comment]
This may be a hard one since trident CEM models are hardcoded in Minecraft.

**Comment by U5B** [comment]
May be fixable by ETF, or Njol's mod.
Either wait for Njol's mod to update to 1.18.2 or rename files to work with ETF.

**Comment by U5B** [comment]
https://discord.com/channels/313066655494438922/481866127471804427/1015931983970451549

Using this version of CIT Resewn should fix it (Thanks @Vladomeme)
https://cdn.discordapp.com/attachments/481866127471804427/1015931984222105630/CITResewn-0.9.11.18.2.jar

**Comment by Vladomeme** [comment]
Fixed by the latest version of Njol's mod.
